### ISSUE TITLE
Error while reading file from ASTEC

### ISSUE THREAD

**Issue by stefanhahmann** [leoguignard/LineageTree#13]
I have tried to run the following script to read a *.pkl file. I am using the astec environment that has been created following these instructions: https://astec.gitlabpages.inria.fr/astec/installation.html#user-installation-without-git

```
import lineageTree

def load_pkl():
    tree = lineageTree.lineageTree()
    tree.read_from_ASTEC(file_path="Astec-U0126-Pm2_properties.pkl", eigen=True)
    print(tree.nodes)


if __name__ == '__main__':
    load_pkl()
```

However, when running this script, I get an error message:

```
C:\Users\s\AppData\Local\mambaforge\envs\astec\python.exe C:\Users\\git\LineageTree\src\LineageTree\load_pkl.py 
Traceback (most recent call last):
  File "C:\Users\s\git\LineageTree\src\LineageTree\load_pkl.py", line 11, in <module>
    load_pkl()
  File "C:\Users\s\git\LineageTree\src\LineageTree\load_pkl.py", line 6, in load_pkl
    tree.read_from_ASTEC(file_path="Astec-U0126-Pm2_properties.pkl", eigen=True)
  File "C:\Users\s\git\LineageTree\src\LineageTree\lineageTree.py", line 1008, in read_from_ASTEC
    prop_values.isinstance(set)
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'isinstance'
```

Any advice would be appreciated. The *.pkl file was extracted from: https://figshare.com/articles/dataset/Astec-U0126-Pm2_U0126_treated_Phallusia_mammillata_embryo_live_SPIM_imaging_stages_7-9_/11307293

**Comment by leoguignard** [comment]
(please reinstall from the repo and not pypi if possible)

**Comment by stefanhahmann** [comment]
Thanks. This solved the problem.
